version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: guy
      WORDPRESS_DB_PASSWORD: 310120
      WORDPRESS_DB_NAME: wp_devcontainer
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 310120
      MYSQL_DATABASE: wp_devcontainer
      MYSQL_USER: guy
      MYSQL_PASSWORD: 310120
    volumes:
      - ./db_data:/var/lib/mysql
